### ISSUE TITLE
Question about which paper is the implementation for

### ISSUE THREAD

**Issue by VespaLan** [arndmghsh/TopicModelling-GaussianLDA-GibbsSampler#2]
Hi~Thanks for sharing your work! I am wondering if this is a re-implementation of the paper  [Gaussian LDA for Topic Models with Word Embeddings](http://rajarshd.github.io/papers/acl2015.pdf)?

**Comment by arndmghsh** [comment]
Hi,

Yes, it's the re-implementation of the paper mentioned by you. Hadn't had the time to add all the details at that time. I will add it to ReadMe. Thanks.
